# Generated by Django 4.2.7 on 2023-11-21 01:56

from django.db import migrations


def up(apps, schema_editor):
    Item = apps.get_model("item", "Item")
    Item.objects.bulk_create(
        [
            Item(name="shoes", description="shoes for the feet", stock=50, price=20.99),
            Item(name="woman clothes", description="For women", stock=800, price=10.50),
            Item(name="men clothes", description="For men", stock=20, price=5),
            Item(name="kids clothes", description="for children", stock=40, price=8),
            Item(name="makeup", description="for vanity", stock=150, price=500),
            Item(
                name="jewerly", description="for luxury people", stock=15, price=5000.59
            ),
            Item(
                name="sun glasses", description="for cool people", stock=20, price=33.33
            ),
            Item(name="sportwear", description="sweat with style", stock=15, price=800),
            Item(name="hat", description="get the old west fashion", stock=8, price=10),
            Item(
                name="earphones",
                description="listen your favorite music",
                stock=18,
                price=63.78,
            ),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("item", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(up),
    ]
