# Generated by Django 4.2.7 on 2023-11-21 09:19

from django.db import migrations


def up(apps, schema_editor):
    DiscountType = apps.get_model("order", "DiscountType")
    DiscountType.objects.bulk_create(
        [
            DiscountType(
                description="Minimum purchase of a certain amount and you get a percentage discount",
                enum="MIN_PURCHASE_AMOUNT__PERCENTAGE_DISCOUNT",
            ),
            DiscountType(
                description="Minimum purchase of a certain stock and you get a fixed discount",
                enum="MIN_PURCHASE_STOCK__FIXED_DISCOUNT",
            ),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(up),
    ]
