# Generated by Django 4.2.7 on 2023-11-21 09:53

from django.db import migrations


def up(apps, schema_editor):
    Discount = apps.get_model("order", "Discount")
    DiscountType = apps.get_model("order", "DiscountType")
    Discount.objects.bulk_create(
        [
            Discount(
                start_date=None,
                end_date=None,
                type="PERCENTAGE",
                discount_quantity=10,
                discount_type=DiscountType.objects.get(pk=1),
                amount_criteria=100,
                quantity_critera=None,
            ),
        ]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_auto_20231121_0919"),
    ]

    operations = [
        migrations.RunPython(up),
    ]
